name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main  # 또는 release 브랜치 이름

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker images
      run: docker-compose build

    - name: Push Docker images
      run: |
        docker-compose push

    - name: Run Docker Compose
      run: |
        docker-compose up -d
